# Generated by Django 5.1.1 on 2024-09-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='project/static/portfolio/images/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('project_url', models.URLField(blank=True)),
            ],
        ),
    ]
